theme: jekyll-theme-merlot
title: ADA Template Website
description: A template website for ADA
show_downloads: True
# navigation:
#   - title: Home
#     url: /
#   - title: "The Pulse of the Market: Who Sets the Rhythm?"
#     url: content
#   - title: Example
#     url: example
header_pages:
  - index.md
  - content.md
  - example.md
