theme: jekyll-theme-minimal
title: ADA Template Website
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: "The Pulse of the Market: Who Sets the Rhythm?"
    url: content
  - title: Analysis of Stock Leadership
    url: analysis
  - title: Example
    url: example
